PoemCastle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('poem_castle.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poem_castle/urls.py
from django.urls import path
from . import views
app_name = 'poem_castle'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('home', views.MainView.as_view(), name='home'),
    path(
        route='collection/<str:slug>',
        view=views.CollectionPoemView.as_view(),
        name='collection'
    ),
    path(
        route='poem/<str:slug>/<int:id>',
        view=views.PoemDetail.as_view(),
        name='poem_detail'
    ),
    path(
        route='all-poems',
        view=views.PoemListView.as_view(),
        name='poem_list'
    ),
    path(
        route='search_results',
        view=views.SearchResultsList.as_view(),
        name='search_results'
    ),
]

poem_castle/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from django.urls import reverse
from cloudinary.models import CloudinaryField
from django.contrib.postgres.search import SearchVectorField
from django.contrib.postgres.indexes import GinIndex

# Create your models here.
class Collection(models.Model):
    name = models.CharField(max_length=500, null=True, blank=True)
    slug = models.SlugField(null=True,  max_length=500)
    # image = CloudinaryField('image', null=True)
    
    class Meta:
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Collection, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('poem_castle:collection_detail',
                       kwargs={'slug': self.slug})
    
class Author(models.Model):
    full_name = models.CharField(null=True, blank=True, max_length=500)

    class Meta:
        ordering = ['full_name']

    def __str__(self):
        return f"{self.full_name}"

class Poem(models.Model):
    collection = models.ForeignKey(Collection, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=500, null=True, blank=True,)
    slug = models.SlugField(null=True,  max_length=500)
    author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL)
    body = RichTextField()
    date_created = models.DateTimeField(auto_now=True)
    featured_image = CloudinaryField('image', null=True)
    add_to_featured_poems = models.BooleanField(default=True)
    search_vector = SearchVectorField(null=True)

    class Meta:
        ordering = ['date_created']
        indexes = [
            GinIndex(fields=["search_vector"]),
        ]

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super(Poem, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('poem_castle:poem_detail', kwargs={'slug': self.slug, 'id': self.id})

poem_castle/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView
from .models import Poem, Collection

# Create your views here.

class LandingPageView(TemplateView):
    template_name = 'index.html'


class MainView(ListView):
    template_name = 'base.html'
    paginate_by = 12
    model = Poem

    def get_queryset(self):
        return Poem.objects.filter(add_to_featured_poems=True).order_by('-date_created')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        featured_poems = Poem.objects.filter(add_to_featured_poems=True).order_by('-date_created')
        collections = Collection.objects.all()
        poems_count =Poem.objects.all().count()
        context['featured_poems'] = featured_poems
        context['collections'] = collections
        context['poems_count'] = poems_count
        return context
    

class AboutView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        collections = Collection.objects.all()
        context['collections'] = collections
        return context
    
class CollectionPoemView(ListView):
    model = Poem
    template_name = "collection_poem.html"
    paginate_by = 12

    def get_queryset(self):
        collection = get_object_or_404(Collection, slug=self.kwargs.get('slug'))
        return Poem.objects.filter(collection=collection).order_by('-date_created')

    def get_context_data(self, *args, **kwargs):
        context = super(CollectionPoemView,
                        self).get_context_data(**kwargs)
        collection = get_object_or_404(Collection, slug=self.kwargs.get('slug'))
        collection_poems = Poem.objects.filter(collection=collection).order_by('-date_created')

        collections = Collection.objects.all()
        

        context['collections'] = collections
        context['collection'] = collection
        context['collection_poems'] = collection_poems
        return context
    
class PoemListView(ListView):
    model = Poem
    context_object_name = 'poems'
    template_name = "poems.html"
    
    paginate_by = 12

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-date_created', 'title')
        return queryset

    def get_context_data(self, **kwargs):
    
        # Call the base implementation first to get the context
        # context = super().get_context_data(**kwargs)
        context = super(PoemListView, self).get_context_data(**kwargs)
        poems = Poem.objects.all().order_by('-date_created', 'title')
        collections = Collection.objects.all()
        context['collections'] = collections
        context['poems'] = poems
        return context

class PoemDetail(DetailView):
    model = Poem
    template_name = 'poem_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        collections = Collection.objects.all()
        poems =Poem.objects.all()
        context['poems'] = poems
        context['collections'] = collections
        return context

from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, SearchHeadline
class SearchResultsList(ListView):
    model = Poem
    context_object_name = "poems"
    template_name = "search.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        search_vector = SearchVector("title", "author", "body")
        search_query = SearchQuery(query)

        search_headline = SearchHeadline("title", search_query)
        return Poem.objects.annotate(
            search=search_vector,
            rank=SearchRank(search_vector, search_query)
        ).annotate(headline=search_headline).filter(search=search_query).order_by("-rank")

poem_castle/templates/about.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'base.html' %}
    {% load static %}
    <head>
        {% block title %}
            <title>About - Solomon Ahamdi Oluwasegun</title>
        {% endblock title %}
    </head>

    <body>
        
        {% block content %}
        <div class="about-container">
            <div class="about-card">
                <div class="about-me-head">
                    <h1 class="about-me-name">Solomon Ahamdi Oluwasegun</h1>
                    
                </div>
                <h4 style="margin-bottom: 30px; border-bottom: #FF008D solid; padding-bottom: 4px; width: fit-content;">Autobiography </h4>
                
                <div class="about-me-body">
                    <p>
                        Solomon Ahamdi Olusegun Onwuka Nee can be said to reflect a true Nigerian born 9th May 1958 to Pa Clement Igbani Onwuka - of Igbo stock from Ndoro Oboro in Ikwuano local government area of Abia state, Nigeria. His mother, Mrs Florence Ajayi Onwuka - (Nee) Soremekun Agbakin, in Egba land in Abeokuta Ogun State in Nigeria.

                    </p> <br>
                    <p>
                        As the first son, I was sent to Ndoro Oboro in Ikwuano Abia state to equip me with the Igbo language and culture. I did my primary education at Methodist Primary School Ndoro Oboro.

                        
                    </p><br>
                    <p>
                        I witnessed the civil war and all the ups and lows. As a battalion commander, my father was among the last batch of "boys company" rejected by the military headquarters at Umuahia, the then capital of Biafra, after the fall of Enugu. Some of my works reflected the civil war experience.
                    </p><br>
                    <p>
                        I returned to Lagos in 1974 to obtain my school certificate in 1979. During this period of my secondary education, the art in me took shape and flourished. I was the 1978/79 Nigeria's premier college Yaba Lagos chapel prefect, dramatic/literary/ debating societies president

                    </p><br>
                    <p>
                        In 1996, I obtained my higher diploma in business administration at Ramat polytechnic, Maiduguri, Borno state, in northern Nigeria.
                    </p><br>
                    <p>
                        I have handled many appointments at the managerial level of both private and public sectors. I have written over 300 poems, plays, and a few novels (Fiction and non-fiction). Most of them are unpublished due to financial constraints.
                    </p><br>
                    <p>
                        I am married to an Okemesi lady Miss Grace Olayiwole and daughter to Pa Joseph Olayiwola Oyeniran and Ma Rachel Abiola Olayiwola family.
                    </p><br>
                    <p>
                        I am blessed with four children, Ezekiel, Gabriel, Samson and Joseph, who are doing exceptionally well in their various fields of profession.
                    </p><br>
                    <p>
                        "A rose for you" is the collection you are appreciating now. Most of these poems were written and translated before I received Christ as my Lord and saviour.
                    </p><br>
                </div>
            </div>
            
        </div>
        {% endblock content %}
        
    </body>
</html>

poem_castle/templates/collection_poem.html
<html lang="en">
    {% extends 'base.html' %}
    {% load static %}
    <head>
        {% block title %}
            <title>{{collection.name}}</title>
        {% endblock title %}
    </head>

    <body>
        {% block content %}
        <div class="featured-poems">
            <div class="featured-poems-heading">
                <h2>{{collection.name}}</h2>
            </div>
            <div class="poem-list-container">
                {% if collection_poems %}
                {% for poem in object_list %}
                <div class="poem-card">
                    <div class="poem-image">
                        <img src="{{poem.featured_image.url}}" alt="">
                    </div>
                    <div class="poem-body">
                        <a href="{{poem.get_absolute_url}}"><h3 class="poem-title">{{poem.title|title}}</h3></a>
                        <p class="poem-date">{{poem.date_created|date:"d M Y"}}</p>
                        <p class="poem-date poem-author">{{poem.author}}</p>
                        <div class="poem-body-container">
                            <p class="poem-short-body">{{poem.body|safe|escape|truncatewords:10}}</p>
                        </div>
                        <a href="{% url 'poem_castle:collection' poem.collection.slug %}"><p class="poem-collection">{{poem.collection}}</p></a>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
                
            </div>
            
        </div>
        {% endblock content %}
        
    </body>
</html>

poem_castle/templates/poem_detail.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'base.html' %}
    {% load static %}
    <head>
        {% block title %}
            <title>{{poem.title}}</title>
        {% endblock title %}
    </head>
    <body>
        {% block content %}
        <div class="poem-detail">
            <div class="poem-detail-container">
                <div class="poem-detail-card">
                    <div class="poem-detail-collection">
                        <a href="{% url 'poem_castle:collection' poem.collection.slug %}">{{poem.collection.name}}</a>
                    </div>
                    <div class="poem-detail-heading">
                        <h1 class="poem-detail-title">{{poem.title}}</h1>
                    </div>
                    <div class="poem-detail-stat">
                        <p>By <span>{{poem.author}}</span></p>
                        <p>- {{poem.date_created|date:"d M Y"}}</p>
                    </div>
                    <div class="poem-detail-share">
                        <div class="socials">
                            <div class="social">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="transform: ;msFilter:;"><path d="M21.593 7.203a2.506 2.506 0 0 0-1.762-1.766C18.265 5.007 12 5 12 5s-6.264-.007-7.831.404a2.56 2.56 0 0 0-1.766 1.778c-.413 1.566-.417 4.814-.417 4.814s-.004 3.264.406 4.814c.23.857.905 1.534 1.763 1.765 1.582.43 7.83.437 7.83.437s6.265.007 7.831-.403a2.515 2.515 0 0 0 1.767-1.763c.414-1.565.417-4.812.417-4.812s.02-3.265-.407-4.831zM9.996 15.005l.005-6 5.207 3.005-5.212 2.995z"></path></svg>
                            </div>
                            <div class="social">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="transform: ;msFilter:;"><path d="M19.59 6.69a4.83 4.83 0 0 1-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 0 1-5.2 1.74 2.89 2.89 0 0 1 2.31-4.64 2.93 2.93 0 0 1 .88.13V9.4a6.84 6.84 0 0 0-1-.05A6.33 6.33 0 0 0 5 20.1a6.34 6.34 0 0 0 10.86-4.43v-7a8.16 8.16 0 0 0 4.77 1.52v-3.4a4.85 4.85 0 0 1-1-.1z"></path></svg>
                            </div>
                            <div class="social">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="transform: ;msFilter:;"><path d="M12.001 2.002c-5.522 0-9.999 4.477-9.999 9.999 0 4.99 3.656 9.126 8.437 9.879v-6.988h-2.54v-2.891h2.54V9.798c0-2.508 1.493-3.891 3.776-3.891 1.094 0 2.24.195 2.24.195v2.459h-1.264c-1.24 0-1.628.772-1.628 1.563v1.875h2.771l-.443 2.891h-2.328v6.988C18.344 21.129 22 16.992 22 12.001c0-5.522-4.477-9.999-9.999-9.999z"></path></svg>
                            </div>
                            <div class="social">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="transform: ;msFilter:;"><path d="M20.947 8.305a6.53 6.53 0 0 0-.419-2.216 4.61 4.61 0 0 0-2.633-2.633 6.606 6.606 0 0 0-2.186-.42c-.962-.043-1.267-.055-3.709-.055s-2.755 0-3.71.055a6.606 6.606 0 0 0-2.185.42 4.607 4.607 0 0 0-2.633 2.633 6.554 6.554 0 0 0-.419 2.185c-.043.963-.056 1.268-.056 3.71s0 2.754.056 3.71c.015.748.156 1.486.419 2.187a4.61 4.61 0 0 0 2.634 2.632 6.584 6.584 0 0 0 2.185.45c.963.043 1.268.056 3.71.056s2.755 0 3.71-.056a6.59 6.59 0 0 0 2.186-.419 4.615 4.615 0 0 0 2.633-2.633c.263-.7.404-1.438.419-2.187.043-.962.056-1.267.056-3.71-.002-2.442-.002-2.752-.058-3.709zm-8.953 8.297c-2.554 0-4.623-2.069-4.623-4.623s2.069-4.623 4.623-4.623a4.623 4.623 0 0 1 0 9.246zm4.807-8.339a1.077 1.077 0 0 1-1.078-1.078 1.077 1.077 0 1 1 2.155 0c0 .596-.482 1.078-1.077 1.078z"></path><circle cx="11.994" cy="11.979" r="3.003"></circle></svg>
                            </div>
                            <div class="social">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="transform: ;msFilter:;"><path d="M19.633 7.997c.013.175.013.349.013.523 0 5.325-4.053 11.461-11.46 11.461-2.282 0-4.402-.661-6.186-1.809.324.037.636.05.973.05a8.07 8.07 0 0 0 5.001-1.721 4.036 4.036 0 0 1-3.767-2.793c.249.037.499.062.761.062.361 0 .724-.05 1.061-.137a4.027 4.027 0 0 1-3.23-3.953v-.05c.537.299 1.16.486 1.82.511a4.022 4.022 0 0 1-1.796-3.354c0-.748.199-1.434.548-2.032a11.457 11.457 0 0 0 8.306 4.215c-.062-.3-.1-.611-.1-.923a4.026 4.026 0 0 1 4.028-4.028c1.16 0 2.207.486 2.943 1.272a7.957 7.957 0 0 0 2.556-.973 4.02 4.02 0 0 1-1.771 2.22 8.073 8.073 0 0 0 2.319-.624 8.645 8.645 0 0 1-2.019 2.083z"></path></svg>
                            </div>
                        </div>
                    </div>
                    <div class="poem-detail-image">
                        <img src="{{poem.featured_image.url}}" alt="">
                    </div>
                    <div class="poem-detail-poem-body">
                        <p class="poem-body-text">{{poem.body|safe}}</p>
                    </div>
                </div>
                <script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="poemcastlea" data-description="Support me on Buy me a coffee!" data-message="Thank you for coming to my page. You can buy me a coffee." data-color="#FF5F5F" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
                <div class="poem-detail-aside">
                    <div class="aside-heading">
                        <h2>In the same collection</h2>
                    </div>
                    <div class="poems-in-the-same-collections">
                        {% for poem_sim in poems|slice:"6"  %}
                        {% if poem_sim.collection.slug == poem.collection.slug %}
                        <div class="poem-card">
                            <div class="poem-image">
                                <img src="{{poem_sim.featured_image.url}}" alt="">
                            </div>
                            <div class="poem-body">
                                <a href="{{poem_sim.get_absolute_url}}"><h3 class="poem-title">{{poem_sim.title|title}}</h3></a>
                                <p class="poem-date">{{poem_sim.date_created|date:"D d M Y"}}</p>
                                <p class="poem-date poem-author">{{poem_sim.author}}</p>
                                <div class="poem-body-container">
                                    <p class="poem-short-body">{{poem_sim.body|safe|escape|truncatewords:10}}</p>
                                </div>
                                <a href="{% url 'poem_castle:collection' poem_sim.collection.slug %}"><p class="poem-collection">{{poem_sim.collection}}</p></a>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        
        {% endblock content %}
        
    </body>
</html>

poem_castle/templates/poems.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'base.html' %}
    {% load static %}
    <head>
        {% block title %}
            <title>All Poems</title>
        {% endblock title %}
    </head>

    <body>
        
        {% block content %}
        <div class="featured-poems">
            <div class="featured-poems-heading">
                <h2>All poems</h2>
            </div>
            <div class="poem-list-container">
                {% if poems %}
                {% for poem in object_list %}
                <div class="poem-card">
                    <div class="poem-image">
                        <img src="{{poem.featured_image.url}}" alt="">
                    </div>
                    <div class="poem-body">
                        <a href="{{poem.get_absolute_url}}"><h3 class="poem-title">{{poem.title|title}}</h3></a>
                        <p class="poem-date">{{poem.date_created|date:"d M Y"}}</p>
                        <p class="poem-date poem-author">{{poem.author}}</p>
                        <div class="poem-body-container">
                            <p class="poem-short-body">{{poem.body|safe|escape|truncatewords:10}}</p>
                        </div>
                        <a href="{% url 'poem_castle:collection' poem.collection.slug %}"><p class="poem-collection">{{poem.collection}}</p></a>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
                
            </div>
        </div>
        {% endblock content %}

        

        
    </body>
</html>

poem_castle/templates/search.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'base.html' %}
    {% load static %}
    <head>
        {% block title %}
            <title>{{poem.title}}</title>
        {% endblock title %}
    </head>
    <body>
        {% block content %}
        <h1>Search Results</h1>

        <div class="search-result-container poem-list-container">
            <br><br>

            {% for poem in poems %}
            
            <div class="poem-card">
                <div class="poem-image">
                    <img src="{{poem.featured_image.url}}" alt="">
                </div>
                <div class="poem-body">
                    <a href="{{poem.get_absolute_url}}"><h3 class="poem-title">{{poem.headline|title|safe}}</h3></a>
                    <p class="poem-date">{{poem.date_created|date:"d M Y"}}</p>
                    <p class="poem-date poem-author">{{poem.author}}</p>
                    <div class="poem-body-container">
                        <p class="poem-short-body">{{poem.body|safe|escape|truncatewords:10}}</p>
                    </div>
                    <a href="{% url 'poem_castle:collection' poem.collection.slug %}"><p class="poem-collection">{{poem.collection}}</p></a>
                </div>
            </div>

            {% empty %}
            <p>No results found. Try again.</p>
            {% endfor %}

            
        </div>
        
        {% endblock content %}
        
    </body>
</html>